# Generated by Django 3.2.3 on 2021-06-14 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dhionathan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Dhionathan.professor'),
            preserve_default=False,
        ),
    ]
