# Generated by Django 3.2.3 on 2021-06-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dhionathan', '0002_auto_20210610_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='periodo',
            field=models.IntegerField(),
        ),
    ]
