# Generated by Django 3.2.3 on 2021-05-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('gerente', models.CharField(max_length=150)),
                ('troco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caixa', models.BooleanField()),
            ],
        ),
    ]
