# Generated by Django 3.2.3 on 2021-05-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanova', '0002_alter_departamento_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=15)),
                ('cargo', models.CharField(max_length=20)),
                ('departamento', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
