# Generated by Django 3.2.3 on 2021-05-25 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zanova', '0003_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zanova.funcionario')),
            ],
            bases=('zanova.funcionario',),
        ),
    ]
