# Generated by Django 3.2.3 on 2021-05-25 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zanova', '0004_gerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='Departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zanova.departamento'),
            preserve_default=False,
        ),
    ]
