# Generated by Django 3.2.3 on 2021-05-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zanova', '0005_funcionario_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='departamento',
        ),
    ]
