# Generated by Django 3.2.3 on 2021-06-01 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zanova', '0008_funcionario_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='Departamento',
            new_name='departamento',
        ),
    ]
