# Generated by Django 3.2.3 on 2021-06-02 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zanova', '0009_rename_departamento_funcionario_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateTimeField()),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zanova.departamento')),
            ],
        ),
    ]
