# Generated by Django 3.2.3 on 2021-06-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dhionathan', '0004_auto_20210610_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data',
            field=models.CharField(max_length=20),
        ),
    ]
