# Generated by Django 3.2.3 on 2021-06-10 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dhionathan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dhionathan.disciplina'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='tipo_de_avaliacao',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dhionathan.professor'),
        ),
        migrations.DeleteModel(
            name='Tipo_de_Avaliacao',
        ),
    ]
