# Generated by Django 3.2.3 on 2021-06-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dhionathan', '0003_alter_disciplina_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='dia_da_semana',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='data',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
